name: "dotnet-exec"
author: "Weihan Li"
description: "dotnet-exec to execute C# script"
branding:
  icon: 'chevron-right'
  color: 'black'
inputs:
  script:
    description: 'Script to execute'
    required: true
  arguments:
    description: 'Script arguments'
    required: false
    default: ""
  options:
    description: 'Script execute options'
    required: false
    default: ""
runs:
  using: 'docker'
  image: 'docker://weihanli/dotnet-exec:0.16.0'
  args:
    - ${{ inputs.script }}
    - ${{ inputs.options }}
    - "--"
    - ${{ inputs.arguments }}
