name: sync-upstream-release

on:
  schedule:
    - cron:  '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
        include-prerelease: true
    - name: Install dotnet-exec
      run: dotnet tool update -g dotnet-execute
    - name: dotnet-exec info
      run: dotnet-exec --info
    - name: Run dotnet-exec
      run: dotnet-exec ./scripts/sync-upstream-release.cs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Detect changes
      run: |
        if git diff --exit-code; then
          echo "HAS_CHANGES=false" >> $GITHUB_ENV
        else
          echo "HAS_CHANGES=true" >> $GITHUB_ENV
        fi
    - name: Create Pull Request
      if: ${{ env.HAS_CHANGES == 'true' }}
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "sync upstream release"
        title: 'Sync Upstream Release'
        body: >
          This PR updates the outdated NuGet packages.
        labels: automated-pr
        branch: sync-upstream-release
        base: ${{ github.ref }}
